### ISSUE TITLE
Questions from TORmem

### ISSUE THREAD

**Issue by betawaffle** [pkoutoupis/rapiddisk#107]
This is not really an issue, more of a discussion. I not sure if there's a better venue for this. If there is, let me know.

First, a bit of context: I work at [TORmem](https://github.com/tormem), and we have a tiny fork of rapiddisk with [modifications to the main kernel module](https://github.com/tormem/rapiddisk/pull/1/files) to suit our use-case. I made these changes myself, and I'm definitely not an expert in either C or kernel development, so take them with a grain of salt.

With that in mind, my question is thus: **Are any of our changes something you might consider pulling in?**

Some of them are almost certainly inappropriate, but a few of them were done to improve resilience to unreasonable input from userspace.

Summary of changes in our fork:

- Attempt to clarify how sizes are specified. Sometimes `size` really means sectors, sometimes bytes, sometimes KiB, etc. I didn't really do this everywhere, only the areas I had to work with.
- Replace some cases of `int` with `unsigned long` and `unsigned long long`. This was mostly to allow the module to correctly handle very large sizes. Not being a C expert, I'm not certain I picked exactly the right types, but it does at least work on the architecture we use.
- Change the output format of `/sys/kernel/rapiddisk/mgmt` to be easier to parse. This is specific to our use-case.
- Move the decision of which device number (e.g. rd0, rd12, ...) to use out of the kernel. Only the uniqueness check remains in the kernel. This lets us know which device to use, even if multiple `attach` commands are in-flight at the same time.
- A few additional checks of input from userspace.

**Comment by pkoutoupis** [comment]
@betawaffle A few things:
1.  This is a perfectly fine place to initiate this discussion.
2. Thank you very much for your (and your company's) interest in my project. I find it both exciting and reassuring that you are all able to make good use of my project.
3. Due to my chaotic schedule, it may take a little bit of time, but of course I will take a look at the changes you made and consider pulling them into the master branch. I just need to understand the changes better.

**Comment by pkoutoupis** [comment]
@betawaffle most of it seems like it can be done, although I will need to relocate the number assignment into userspace. The only thing that requires a discussion is the output of `rapiddisk/mgmt`. I have a thought on that. I will put together a pull request in the coming days and we can work through that to ensure that you get what you need and with as little disruption to existing users.

**Comment by betawaffle** [comment]
Thanks, sounds great!

**Comment by pkoutoupis** [comment]
@betawaffle This is a mockup and won't reflect the end result but would this help you?
```
petros@goddamnit:~/devel/rapiddisk/src$ cat /sys/kernel/rapiddisk/mgmt 
RapidDisk 8.2.0

Maximum Number of Attachable Devices: 256
Number of Attached Devices: 5
Max Sectors (KB): 127
Number of Requests: 128

Device	Size	Errors
rd0	64	0
rd1	128	0
rd2	128	0
rd3	64	0
rd4	256	0
```
This way, you can get something parsable while we can continue to retain the other module information. Thoughts?

**Comment by betawaffle** [comment]
It might work if I know how many lines to skip. My worry with that is it might be fragile. If we decided to add more info to the output later, it would break the code reading from it. That could be avoided if we settle on a well-defined structure to the output, and I could just parse all of it. Something like:

```
RapidDisk <version>
(empty line)
... multiple lines of human-friendly info, no empty lines ...
(empty line)
<table header>
... table rows ...
```

We'd have to actually define all the details to make it reliably parsable.

Another option (that would be more work) would be to add a new file designed to be machine-friendly rather than human-friendly.

A third option would be to keep this, and add a new mechanism for pulling this info from the kernel.

**Comment by pkoutoupis** [comment]
If we stick with a format/structure like this (and I can make it more formal and better documented in the project wiki):
```$ cat /sys/kernel/rapiddisk/mgmt 
RapidDisk 8.2.0

Maximum Number of Attachable Devices: 256
Number of Attached Devices: 5
Max Sectors (KB): 127
Number of Requests: 128

Device	Size	Errors
rd0	64	0
rd1	128	0
rd2	128	0
rd3	512	0
rd4	256	0
```
We can easily parse it as so, regardless of how much info we decide to add before it:
```
$ sed '1,/Errors$/d' /sys/kernel/rapiddisk/mgmt 
rd0	64	0
rd1	128	0
rd2	128	0
rd3	512	0
rd4	256	0
```
Unless I am misunderstanding something.

**Comment by betawaffle** [comment]
I'm parsing it from rust, so it's slightly more difficult than that :stuck_out_tongue:

**Comment by pkoutoupis** [comment]
So, a new file like this?
```
$ cat /sys/kernel/rapiddisk/devices
Device	Size	Errors
rd0	256	0
rd1	256	0
rd2	64	0
```

**Comment by betawaffle** [comment]
That would work, yeah.

**Comment by pkoutoupis** [comment]
Sounds good. I have been testing the changes being made as I go along. I just need to wrap up with the "attach" logic in the user space utility and then I will open the PR for review with the details. I am hoping tonight or tomorrow.

**Comment by pkoutoupis** [comment]
@betawaffle I pushed another update. Go for it.

**Comment by betawaffle** [comment]
Ok, did a bit of testing. Here are some findings:

- The size reported by `devices` is always zero.
- The default mentioned on [line 97](https://github.com/pkoutoupis/rapiddisk/compare/pkoutoupis:a509fe4...pkoutoupis:79dd427#diff-93123f8261a5700c992d3dc93cfb9bed872469dd18db46a3a58033eb78ea4514R97) doesn't seem to agree with `MAX_RDSKS`.
- It _seems_ to double the size specified in the `attach` command. For example, if I write `rapiddisk attach 0 512`, it creates a `1K` block device, as seen by `lsblk`. I remember running into this with my own version, and I fixed it somewhere.
- [Line 750](https://github.com/pkoutoupis/rapiddisk/compare/pkoutoupis:a509fe4...pkoutoupis:79dd427#diff-93123f8261a5700c992d3dc93cfb9bed872469dd18db46a3a58033eb78ea4514R750) seems like a weird place to use `SUCCESS`.
- [Line 768](https://github.com/pkoutoupis/rapiddisk/compare/pkoutoupis:a509fe4...pkoutoupis:79dd427#diff-93123f8261a5700c992d3dc93cfb9bed872469dd18db46a3a58033eb78ea4514R768) should be deleted.
- Same comment about `SUCCESS` on [line 925](https://github.com/pkoutoupis/rapiddisk/compare/pkoutoupis:a509fe4...pkoutoupis:79dd427#diff-93123f8261a5700c992d3dc93cfb9bed872469dd18db46a3a58033eb78ea4514R925).
- The types of the module params, and the static variables do not agree (`long` vs `unsigned long`) for `rd_nr`, `rd_size`, and `rd_max_nr`. I didn't actually test to see if I could use this to break something.
- The `MINORMASK` check works correctly.
- I can create a 512TiB block device, hooray! I should probably test the limits further, but that's more than enough for my needs.

Otherwise, everything looks good!

**Comment by pkoutoupis** [comment]
I fixed the following and will push soon:
- The default mentioned on [line 97](https://github.com/pkoutoupis/rapiddisk/compare/pkoutoupis:a509fe4...pkoutoupis:79dd427#diff-93123f8261a5700c992d3dc93cfb9bed872469dd18db46a3a58033eb78ea4514R97) doesn't seem to agree with MAX_RDSKS.
- [Line 750](https://github.com/pkoutoupis/rapiddisk/compare/pkoutoupis:a509fe4...pkoutoupis:79dd427#diff-93123f8261a5700c992d3dc93cfb9bed872469dd18db46a3a58033eb78ea4514R750) seems like a weird place to use SUCCESS.
- [Line 768](https://github.com/pkoutoupis/rapiddisk/compare/pkoutoupis:a509fe4...pkoutoupis:79dd427#diff-93123f8261a5700c992d3dc93cfb9bed872469dd18db46a3a58033eb78ea4514R768) should be deleted.
- Same comment about SUCCESS on [line 925](https://github.com/pkoutoupis/rapiddisk/compare/pkoutoupis:a509fe4...pkoutoupis:79dd427#diff-93123f8261a5700c992d3dc93cfb9bed872469dd18db46a3a58033eb78ea4514R925).
- The types of the module params, and the static variables do not agree (long vs unsigned long) for rd_nr, rd_size, and rd_max_nr. I didn't actually test to see if I could use this to break something.

Good catches with some of them. It has been many years since I touched this module outside of kernel support updates. Regarding the SUCCESS part. I hate magic numbers but on second thought, I guess using a 0 there is fine.

These two however are a result of me not understanding the input here (https://github.com/tormem/rapiddisk/pull/1/files):

- The size reported by devices is always zero.
- It seems to double the size specified in the attach command. For example, if I write rapiddisk attach 0 512, it creates a 1K block device, as seen by lsblk. I remember running into this with my own version, and I fixed it somewhere.

For instance, you are expecting an `unsigned long long` (a very large number) but using an input of 512. 512 what? MBs? Bytes? The user space utility handles that. It would be easier to go over this with a screenshare or over the phone but that is ok, we will make do. If it is MBs for example, then the following doesn't make much sense:
```
sectors = size / BYTES_PER_SECTOR;
```
In your example, 512 / BYTES_PER_SECTOR will yield 1.

Anyway, a clarification of your expected input would help and be greatly appreciated.

**Comment by betawaffle** [comment]
> For instance, you are expecting an `unsigned long long` (a very large number) but using an input of 512. 512 what? MBs? Bytes?

I'm passing bytes, since that's the easiest to understand, and it's consistent. Some other options I rejected:

- Sectors, since they are _usually_ 512 bytes, but... not always?
- Kibibytes, since then you couldn't create a... one sector device (heh).
- Mibibytes, for the same reason. It limits how small the device can be.

Anyway, the desired behavior is, userspace asks for bytes, and they get a device with exactly that many bytes (except that it must be a multiple of the sector size, for hopefully obvious reasons).

**Comment by pkoutoupis** [comment]
Pushed new code. Let me know how it looks.

**Comment by betawaffle** [comment]
> Pushed new code. Let me know how it looks.

Everything works and looks good to me! I'll see what needs to change in my API code, but we should be able to proceed with this. Thanks!

**Comment by betawaffle** [comment]
One more question, how confident are you nobody else is depending on the old format of `mgmt` commands?

**Comment by pkoutoupis** [comment]
I thought about the same thing. I will need to document it in changelog, release posts and project wiki. Although, most that use it, I believe utilize the userspace utility that accompanies the modules which would essentially make this a non-issue.

**Comment by pkoutoupis** [comment]
Oh, and I want to run a few more tests before I officially merge it into master, which will be soon.

**Comment by betawaffle** [comment]
There is a way you could remain backwards compatible, but it would be a lot of extra work. Basically, use the `rapiddisk` prefix of the command for versioning. `rapiddisk` would remain the old format, `rapiddisk-v2` would be the new format.

Not sure it's worth the trouble.

**Comment by pkoutoupis** [comment]
I wouldn't be worth it IMHO. I will just need to make sure to document it really well.

**Comment by pkoutoupis** [comment]
Merged the code to master (https://github.com/pkoutoupis/rapiddisk/pull/110). Closing ticket.

Also, @betawaffle, can you please e-mail me at petros AT petroskoutoupis DOT com (_I enjoy seeing folks use my code and am intrigued to learn more_)?
