### ISSUE TITLE
rapiddisk --cache-map on boot/fstab  (ubuntu)

### ISSUE THREAD

**Issue by syadnom** [pkoutoupis/rapiddisk#22]
this works:
umount -f /dev/sda4
rapiddisk --attach 2048
rapiddisk --cache-map rd0 /dev/sda4
mount /dev/mapper/rc-wt_sda4

but to get this on reboot I'm having to do a startup script in /etc/rc.local

Is there a more elegant way?  ie, via fstab?

Thanks.

**Comment by syadnom** [comment]
that wasn't very detailed.  

so, to clarify, I'm wondering if there are some startup/shutdown scripts or other niceties to make this more safe.  What happens when you shutdown without --flush rddev?  data loss or does it flush on unmount?

**Comment by pkoutoupis** [comment]
Unfortunately, there is no elegant way to do this. rc.local is what most folks rely on to "auto" create/mount everything on system boot up. Also, the --flush command is used only when you want to destroy/truncate the data on the actual RAM drive. It is not advisable to use it with a cache mapping. Because of all of the variations that could exist (i.e. RAM drive size, source device, mount point, et al), I cannot imagine that a startup/shutdown init script would look any cleaner.

What the flush routine does is drop all of the memory pages that RapidDisk is using. If you recall from the driver documentation, memory pages are allocated as needed. So if you overprovision a RAM drive to be 1TB in size but are only consuming 2GB, you will only occupy a 2GB footprint in RAM. The flush will drop that back down to 0.

**Comment by syadnom** [comment]
I misunderstood “flush” in this context.  What I was thinking was a
traditional “write everything outstanding to disk right now”

**Comment by pkoutoupis** [comment]
As it stands, every write sent to the cache always persists to the backing store (i.e. the source device). RapidDisk-Cache only supports two modes for write operations: Pass-through and Write-Around. There is no case in which cached data will not be on disk, so a flush is not necessary in its current release. However, if a write-back cache were implemented, then a proper "flush" would be required when disabling the mapping.

Also, I will be closing this issue and will respond to your other comments shortly.

**Comment by bartoszek** [comment]
Just speculating. Could it be achieved with `initcpio hook` ? Add custom `rapidram` hook between `base` and `init` that creates `rapiddisk` cache before `init` mounts `/usr`. Than we just need to mess a bit in `/etc/fstab` :thinking:

**Comment by pkoutoupis** [comment]
I am not very familiar with this concept or process. Assuming that the root file system is mounted and that the rapiddisk (and dmsetup) binaries are accessible, I do not see why it cannot work.

**Comment by bartoszek** [comment]
More or less... it's executed from initrd, before real root get mounted, to
benefit from rapiddisk on root partition too😁

sob., 20 kwi 2019, 16:26 użytkownik Petros Koutoupis '
notifications@github.com' via 33Mail <sender@mailer1.33mail.com> napisał:
