### ISSUE TITLE
Adding openSUSE repo from YaST GUI fails

### ISSUE THREAD

**Issue by bberberov** [pkoutoupis/rapiddisk#24]
Just tried to add the v5 repo and I'm getting the following error.  This was the URL: http://downloads.rapiddisk.org/pub/releases/5/opensuse42/

> An error occurred during repository initialization. [RapidDisk|http://downloads.rapiddisk.org/pub/releases/5/opensuse42/] Valid metadata not found at specified URL History: - File /var/tmp/TmpFile.iRC4XH doesn't contain public key data

**Comment by bberberov** [comment]
Looks like you cannot disable the GPG check through the GUI.  We should build a proper (YaST) openSUSE repo.

**Comment by pkoutoupis** [comment]
@bberberov, 

I haven't commented on this issue yet but that is partly because I do not know if I want to continue supporting the package repos. The upkeep with every official release, especially as it pertains to the latest and greatest release of each respective distro, is quite consuming. So, I have been weighing the option recently, on whether I should continue doing this or just retire them.

Please note, this does not in any way, invalidate the build scripts included in the source code (i.e. the SPEC files). I will continue to maintain those for individuals to run local package builds.

Thoughts? I am also open to suggestions.

**Comment by bberberov** [comment]
I think having official packages helps with exposure/popularity/adoption.  Yes, it is a lot of work.  I'm just thinking, of the people interested in trying RapidDisk, how many don't try it because there isn't a ready built package available.

It'd be nice if third-party repos adopt the package, since those devs have more experience with their respective distros, but in the meantime, you may want to provide repos of your own.  You'll have to choose winners and losers.  For example, recently Solus has been picking up speed, but you don't have a Solus package/repo.

I think automating the build and repo maintenance process would be the way to go.  I don't have experience with the CI tools, but this would be a reason to learn.  GitLab provides free build capacity in their repos if needed.

I think I have figured out the openSUSE `spec` variant, but I haven't figured out the YaST repo structure fully yet to test it.  WIP.

**Comment by pkoutoupis** [comment]
I have since stepped away from packaging RapidDisk for the various distros out in the wild. It was a ton of work to maintain development environments to build, package and test each release. I will fully support those who are willing to do this work in their preferred distros and am also willing to link to it from the project wiki.
