### ISSUE TITLE
kill_bdev disappeared from linux kernel >= 5.8

### ISSUE THREAD

**Issue by marcelhuberfoo** [pkoutoupis/rapiddisk#49]
Unfortunately big changes in linux kernel 5.8 also lead to some cleanup in sections regarding block devices.

The function [`kill_bdev`](https://elixir.bootlin.com/linux/v5.8.1/source/fs/block_dev.c#L78), required by [rapiddisk.c](https://github.com/pkoutoupis/rapiddisk/blob/master/module/rapiddisk.c) is not exported anymore in [fs.h](https://elixir.bootlin.com/linux/v5.7.16/source/include/linux/fs.h#L2593).

A quick fix would be to copy/paste the small function referenced above directly from the kernel source but this would for sure not be a clean solution.

**Comment by marcelhuberfoo** [comment]
An update on this, forgot to add the log output :innocent: 

```
DKMS make.log for rapiddisk-6.1.0 for kernel 5.8.1-arch1-1 (x86_64)
Do 20 Aug 2020 11:10:54 CEST
make: Entering directory '/usr/lib/modules/5.8.1-arch1-1/build'
  AR      /var/lib/dkms/rapiddisk/6.1.0/build/built-in.a
  CC [M]  /var/lib/dkms/rapiddisk/6.1.0/build/rapiddisk.o
  CC [M]  /var/lib/dkms/rapiddisk/6.1.0/build/rapiddisk-cache.o
/var/lib/dkms/rapiddisk/6.1.0/build/rapiddisk.c: In function ‘rdsk_ioctl’:
/var/lib/dkms/rapiddisk/6.1.0/build/rapiddisk.c:632:4: error: implicit declaration of function ‘kill_bdev’; did you mean ‘kill_device’? [-Werror=implicit-function-declaration]
  632 |    kill_bdev(bdev);
      |    ^~~~~~~~~
      |    kill_device
cc1: some warnings being treated as errors
make[1]: *** [scripts/Makefile.build:281: /var/lib/dkms/rapiddisk/6.1.0/build/rapiddisk.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:1756: /var/lib/dkms/rapiddisk/6.1.0/build] Error 2
make: Leaving directory '/usr/lib/modules/5.8.1-arch1-1/build'
```

**Comment by pkoutoupis** [comment]
@marcelhuberfoo: thank you for discovering this and filing the issue. I have been working on a branch with a very large overhaul of the software suite. I am debating on whether I patch this now in a minor update or just include it in that branch for the much larger.

I assume that I may need to replace kill_bdev(bdev) with __invalidate_device(bdev, true) or most likely with invalidate_bdev(bdev). I will try to test this out shortly.

**Comment by marcelhuberfoo** [comment]
As I can easily switch to using a 5.4.x LTS kernel for which the module compiles just fine, you can decide what fits best.

**Comment by pkoutoupis** [comment]
@marcelhuberfoo: I pushed the kernel change to version 7.0.0 which lives in my branch: feature/rapiddiskd_api_daemon. This branch marks a bit of an overhaul for the entire userspace utility and also adds a daemon to listen over the network for REST requests. It would be great if I had a second individual just checking things out and making sure it is stable.

In order to build, you will need the dev libraries for libjansson and libmicrohttpd. Full API support for the daemon with examples are found in doc/API.txt. The rapiddisk utility is also relying on getopt which has changed argument inputs. The rapiddisk.1 manpage reflects those changes.

**Comment by pkoutoupis** [comment]
Pushed into master and tagged in release 7.0.0.
