### ISSUE TITLE
Cannot active writeback on root partition

### ISSUE THREAD

**Issue by ia2130** [pkoutoupis/rapiddisk#70]
Ubuntu 20.04.2
Kernel  5.11.0-40-generic
/dev/sda1 - root partition

Editing
rapiddisk_hook
adding in line 31
manual_add_modules dm-writecache

and in file rapiddisk_sub.orig
adding in line 5
modprobe -v dm-writecache

run  install_initrd.sh --install --root=/dev/sda1 --size=2048 --kernel=5.11.0-40-generic
but after reboot I see error message 
device-mapper: core: Cannot calculate initial queue limits
![Screenshot_cache](https://user-images.githubusercontent.com/44071475/142792441-1ba29f02-733e-4630-9c39-98ccfa15fed4.png)

Please help

**Comment by Augusto7743** [comment]
You need add in file rapiddisk_sub.orig

rapiddisk -a YOURRAMDISKSIZEFORWRITEBACK
rapiddisk -m rd1 /dev/sda1

When running install_initrd.sh --install --root=/dev/sda1 --size=2048 --kernel=5.11.0-40-generic
Use a small value for size because the value will be used for writearound cache and not for the writeback cache.
If you not wait use writearound for root use --size=1 thus will allow install modules in boot.

**Comment by ia2130** [comment]
in  rapiddisk_sub.orig I am  add

rapiddisk -a 512
rapiddisk -m rd1 /dev/sda1

then run install_initrd.sh --install --root=/dev/sda1 --size=128 --kernel=5.11.0-40-generic
and OS cannot boot(
(https://user-images.githubusercontent.com/44071475/142869144-6cbcc81f-6742-4f40-85c2-4ea7dfafbc69.png)

**Comment by Augusto7743** [comment]
I recommend install VirtualBox and create a virtual machine installing Ubuntu creating a partition for boot and another for root.
In moment testing in VM. Sometimes happen the same problem when starting even using correct commands in script.
Trying figure because happen that issue and how create a script to run in shutdown and restart because only creating the cache not automatically flush the data when OS shutdown.

**Comment by ia2130** [comment]
Thank you, for your answers. Can you tell me how I can check did cache is working?
I am mouth other storage
rapiddisk -a 2048
rapiddisk -m rd0 -b /dev/sdl1 -p wb
mount /dev/mapper/rc-wb_sdl1 /storesdl/
rapiddisk -l

> rapiddisk 7.2.1

> Copyright 2011 - 2021 Petros Koutoupis

> List of RapidDisk device(s):

>  RapidDisk Device 1: rd0        Size (KB): 4194304

> List of RapidDisk-Cache mapping(s):

>  dm-writecache Target   1: rc-wb_sdl1   Cache: rd0  Target: sdl1 (WRITEBACK)

And I want to check did I have acceleration on it
