### ISSUE TITLE
How do I cache-map?

### ISSUE THREAD

**Issue by colbyshores** [pkoutoupis/rapiddisk#75]
how do I cache map like the directions here show: https://delightlylinux.wordpress.com/2017/02/15/rapiddisk-improved-hard-drive-caching/
sudo rapiddisk --cache-map rd0 /dev/sdc1

The man pages are very unclear on what replaces it nor could I find any information anywhere online to what it's replacement would be.
Im looking to cache my primary drive(SSD) to a ramdisk for much faster performance.  Is this possible and am I on the right track?  I am uninstalling this daemon/modules until I know for sure that none of this will negatively effect my workstation.
Thanks!

**Comment by pkoutoupis** [comment]
@colbyshores: Hello! Since version 7.0, the administration utility input has changed quite a bit. I have written this script to maintain the legacy input: https://github.com/pkoutoupis/rapiddisk/blob/master/scripts/rapiddisk-legacy/rapiddisk-legacy.sh
But if you are using 7.0 or later:
```
$ sudo rapiddisk -m rd1 -b /dev/sdb
```
Or if you want to specify the cache policy (write-around [wa], write-through [wt] or the volatile write-back [wb]):
```
$ sudo rapiddisk -m rd1 -b /dev/sdb -p wa
```

But in order to map a RAM drive, you need to create one first:
```
$ sudo rapiddisk -a 64
```

**Comment by colbyshores** [comment]
Ok thanks!

**Comment by pkoutoupis** [comment]
No problem. If you have additional questions, please do not hesitate to ask.
